apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
  labels:
    {{- include "study.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.secret.db.host | quote }}
  DB_PORT: {{ .Values.secret.db.port | quote }}
  DB_NAME: {{ .Values.secret.db.name | quote }}
  DB_USER: {{ .Values.secret.db.user | quote }}
  DB_PASSWORD: {{ .Values.secret.db.password | quote }}
  REDIS_HOST: {{ .Values.secret.redis.host | quote }}
  REDIS_PORT: {{ .Values.secret.redis.port | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redis.password | quote }}
  JWT_SECRET: {{ .Values.secret.jwt.secret | quote }}
