apiVersion: v1
kind: Service
metadata:
  name: user-manage
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "study.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: user-manage
  ports:
    - port: 8080
      targetPort: 8080
